[theme]
primaryColor = "#27AE60"          # green buttons
backgroundColor = "#003C43"       # dark background
secondaryBackgroundColor = "1C1F26"
textColor = "#F1C40F"             # gold text
font = "times new roman"